import Navbar from '../components/Navbar';

import '../styles/globals.css';

export const metadata = {
  title: 'Rick and Morty',
  description: 'Generated by Next.js'
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="app">
          <Navbar />
          <main className='app__main'>{children}</main>
        </div>
      </body>
    </html>
  );
}
