import Navbar from '../components/Navbar';
import Sidebar from '../components/Sidebar';

import '../styles/globals.css';

export const metadata = {
  title: 'Rick and Morty',
  description: 'Generated by Next.js'
};

export default function RootLayout({ children, ...rest }) {
  console.log('rest', rest);
  return (
    <html lang="en">
      <body>
        <div className="app">
          <Navbar />
          <main>
            <div className="app__sidebar">
              <Sidebar />
            </div>
            <div className="app__main">{children}</div>
          </main>
        </div>
      </body>
    </html>
  );
}
